1 'OGKE@AI@H@B@@@BD@CBFAEDK@@@ALKEL@@ICADDKLKELILDFACDKLJELACDKIB@@LKELMBAHEC@@LKAHAKAHAOHHCK@@CH@@BCDAJEALBHDACCD@FCDD@E@@EK@A@@IHLKAHAKAHI@B@CED@@@@AEKAIAKAHFHDF@@GI@DCDAHG@A@BLNHMAI@KBONKML@DF
2 'OJ@H@@@@OL@H@@@@LN@H@@@@NN@H@@@@
3 O=#C04:D=0:FORJ=0TO1:N=PEEK(O-2):FORI=0TON/2-2:POKE#700+D,(PEEK(O+i*2)-64)<<4+PEEK(O+1+i*2)-64:D=D+1:NEXT:O=O+N+4:NEXT
