1 'H@BCD@@@AK@A@HAHL@AHOHBCO@KE@@BB@CBDILDF@@HH@EKBBN@@BK@@IGALCNDAACDACG@@BCD@@JCCEK@A@EDNBGD@LKAHMKAIIKAIFFDF@DCBANG@A@BJNLMAO@KM@J@I@@@@
2 O=#C04:FORI=0TO68:POKE#700+I,(PEEK(O+I*2)-64)<<4+PEEK(O+1+I*2)-64:NEXT
