1 'OGKE@HB@@NDK@@IC@NDK@AIC@HBCAMAJ@@BCFJDFN@BFILELOF@@LJAHIGAIBF@@BNDACNG@NEBFHDD@OF@@IBAI@ACCADG@@HBKNNMA@ACH@HCA@@BHNGMAONKML@DFAHAHBDCDKMKMOOEJ
2 O=#C04:FORI=0TO72:POKE#800+I,(PEEK(O+I*2)-64)<<4+PEEK(O+1+I*2)-64:NEXT
