1 'I@BCO@KE@GBDAK@ALNAHA@DJA@DKHJEJLKEJEB@AALD@MK@HMCAHBE@@OOB@@@BBOAAH@OGHN@CE@@@BIGDB@AMA@B@@@MG@@ACCOCAHAIGH@@BI@CMA@HCEOOCBAMG@IBKBB@DAI@DCH@KBO@KML@DFOL@H@@@@OJ@H@@@@
2 O=#C04:FORI=0TO84:POKE#800+I,(PEEK(O+I*2)-64)<<4+PEEK(O+1+I*2)-64:NEXT
